branch-defaults:
  master:
    environment: kula-worker
global:
  application_name: kula
  default_ec2_keyname: kula-ec2-dev
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
